ALTER TYPE "PTORequestType" ADD VALUE IF NOT EXISTS 'PERSONAL';
ALTER TYPE "PTORequestType" ADD VALUE IF NOT EXISTS 'VACATION';
ALTER TYPE "PTORequestType" ADD VALUE IF NOT EXISTS 'SICK';
ALTER TYPE "PTORequestType" ADD VALUE IF NOT EXISTS 'EMERGENCY';

CREATE TYPE "ClinicScenario" AS ENUM ('ROUTINE', 'CLINIC_CLOSED', 'DOCTOR_OFF_REDUCED_STAFFING', 'CUSTOM');

ALTER TABLE "ScheduleDay" ADD COLUMN "scenario" "ClinicScenario" NOT NULL DEFAULT 'ROUTINE';

ALTER TABLE "TaskType" ADD COLUMN "optional" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TaskType" ADD COLUMN "defaultForRoutine" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TaskType" ADD COLUMN "defaultForReduced" BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX "TaskType_optional_idx" ON "TaskType"("optional");
