ALTER TABLE "PTORequest" ADD COLUMN "shortNotice" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TaskSlot" ADD COLUMN "shortNotice" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Assignment" ADD COLUMN "shortNotice" BOOLEAN NOT NULL DEFAULT false;
