ALTER TYPE "SchedulingRuleType" ADD VALUE IF NOT EXISTS 'PREFER_EMPLOYEE_FOR_TASK';
ALTER TYPE "SchedulingRuleType" ADD VALUE IF NOT EXISTS 'AVOID_EMPLOYEE_FOR_TASK';
ALTER TYPE "SchedulingRuleType" ADD VALUE IF NOT EXISTS 'PRIORITY_PENALTY';

ALTER TABLE "SchedulingRule" ADD COLUMN "notes" TEXT;
